---
kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.9.2/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: build
    image: golang
    commands:
      - make build
      - make build-npm

  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files:
        - ls-lint-darwin
        - ls-lint-darwin-arm64
        - ls-lint-linux
        - ls-lint-linux-arm64
        - ls-lint-windows.exe
    when:
      event: tag

  - name: npm
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: npm
      access: public
      tag: beta
    when:
      event: tag

---
kind: pipeline
type: docker
name: docker-linux-amd64
depends_on:
  - main
trigger:
  event:
    - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang
    commands:
      - make build
  - name: docker hub
    image: plugins/docker:linux-amd64
    settings:
      username: loeffel
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: docker/Dockerfile
      auto_tag: true
      auto_tag_suffix: linux-amd64
      repo: lslintorg/ls-lint

---
kind: pipeline
type: docker
name: docker-linux-arm64
depends_on:
  - main
trigger:
  event:
    - tag

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: golang
    commands:
      - make build
  - name: docker hub
    image: plugins/docker:linux-arm64
    settings:
      username: loeffel
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: docker/Dockerfile.arm64
      auto_tag: true
      auto_tag_suffix: linux-arm64
      repo: lslintorg/ls-lint

---
kind: pipeline
type: docker
name: docker-manifest
depends_on:
  - docker-linux-amd64
  - docker-linux-arm64
trigger:
  event:
    - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    pull: always
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      spec: docker/manifest.tmpl
      repo: lslintorg/ls-lint
      username: loeffel
      password:
        from_secret: DOCKER_PASSWORD
