kind: pipeline
type: docker
name: docker

steps:
  - name: linter
    image: golangci/golangci-lint
    commands:
      - make install
      - make linter

  - name: test
    image: golang
    commands:
      - make install
      - make test-coverage
      - make build